"""add base_currency to users

Revision ID: f02387ac00f2
Revises: ea2a874297ee
Create Date: 2025-09-26 15:55:27.099927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02387ac00f2'
down_revision: Union[str, None] = 'ea2a874297ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_currency', sa.String(), nullable=False, server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_currency')
    # ### end Alembic commands ###
