-- Create databases for all services
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS category_db;
CREATE DATABASE IF NOT EXISTS expense_db;
CREATE DATABASE IF NOT EXISTS income_db;
CREATE DATABASE IF NOT EXISTS recurring_db;
CREATE DATABASE IF NOT EXISTS goals_db;
CREATE DATABASE IF NOT EXISTS debt_db;
CREATE DATABASE IF NOT EXISTS account_db;
CREATE DATABASE IF NOT EXISTS subscription_db;
CREATE DATABASE IF NOT EXISTS currency_db;

-- Grant permissions to postgres user
GRANT ALL PRIVILEGES ON DATABASE user_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE category_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE expense_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE income_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE recurring_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE goals_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE debt_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE account_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE subscription_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE currency_db TO postgres;