# Используем официальный образ Python
FROM python:3.14-slim

# Устанавливаем Poetry и postgresql-client для pg_isready
RUN pip install --upgrade pip && pip install poetry \
 && apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# Указываем рабочую директорию
WORKDIR /app

# Копируем зависимости и устанавливаем
COPY expense_service/pyproject.toml expense_service/poetry.lock* ./
RUN poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-ansi

# Копируем код приложения
COPY expense_service/ .

# Копируем общую директорию логирования
COPY logging/ /app/logging

# Делаем startup script исполняемым
RUN chmod +x startup.sh

# Открываем порт и запускаем сервер через startup script
CMD ["./startup.sh"]