"""Add account_id to incomes

Revision ID: 001
Revises: 
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_account_id_to_incomes'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incomes_account_id'), 'incomes', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomes_account_id'), table_name='incomes')
    op.drop_column('incomes', 'account_id')
    # ### end Alembic commands ###
