auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Retention policies
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_parallelism: 32
  max_query_series: 100000
  max_query_length: 721h
  max_query_lookback: 721h
  max_entries_limit_per_query: 5000
  max_streams_per_user: 10000
  max_line_size: 256000
  max_line_size_truncate: true
  
  # Retention by log level
  retention_period: 720h  # 30 days default
  
  # Per-stream limits
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  
  # Ingestion limits
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32

# Compaction
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

# Frontend configuration
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true

# Distributor
distributor:
  ring:
    kvstore:
      store: inmemory

# Ingester
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

# Querier
querier:
  max_concurrent: 20
  query_timeout: 300s
  engine:
    timeout: 300s
    max_look_back_period: 0s
