"""add_parent_id_to_categories_and_remove_subcategories

Revision ID: c6d7e35a6e52
Revises: a3d3777b68f1
Create Date: 2025-09-23 15:20:07.748966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d7e35a6e52'
down_revision: Union[str, None] = 'a3d3777b68f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subcategories_id', table_name='subcategories')
    op.drop_index('ix_subcategories_name', table_name='subcategories')
    op.drop_index('ix_subcategories_user_id', table_name='subcategories')
    op.drop_table('subcategories')
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.create_table('subcategories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='subcategories_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subcategories_pkey')
    )
    op.create_index('ix_subcategories_user_id', 'subcategories', ['user_id'], unique=False)
    op.create_index('ix_subcategories_name', 'subcategories', ['name'], unique=False)
    op.create_index('ix_subcategories_id', 'subcategories', ['id'], unique=False)
    # ### end Alembic commands ###
