"""seed_mcc_codes

Revision ID: seed_mcc_codes
Revises: add_category_fields_for_mcc
Create Date: 2025-01-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'seed_mcc_codes'
down_revision: Union[str, None] = 'add_category_fields_for_mcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Seed mcc_codes table with hardcoded data."""
    # Insert all MCC codes directly in SQL
    op.execute("""
        INSERT INTO mcc_codes (mcc_code, name, is_default, created_at, updated_at) VALUES
        (5411, 'Grocery Stores, Supermarkets', TRUE, NOW(), NOW()),
        (5812, 'Eating places and Restaurants', TRUE, NOW(), NOW()),
        (5542, 'Automated Fuel Dispensers', TRUE, NOW(), NOW()),
        (5814, 'Fast Food Restaurants', TRUE, NOW(), NOW()),
        (5912, 'Drug Stores and Pharmacies', TRUE, NOW(), NOW()),
        (7230, 'Barber and Beauty Shops', TRUE, NOW(), NOW()),
        (742, 'Veterinary Services', TRUE, NOW(), NOW()),
        (5300, 'Wholesale Clubs', TRUE, NOW(), NOW()),
        (5399, 'Misc. General Merchandise', TRUE, NOW(), NOW()),
        (5732, 'Electronic Sales', TRUE, NOW(), NOW()),
        (5813, 'Drinking Places, Bars', TRUE, NOW(), NOW()),
        (4900, 'Electric, Gas, Sanitary and Water Utilities', TRUE, NOW(), NOW()),
        (8011, 'Doctors and Physicians (Not Elsewhere Classified)', TRUE, NOW(), NOW()),
        (5945, 'Hobby, Toy, and Game Shops', TRUE, NOW(), NOW()),
        (5499, 'Misc. Food Stores – Convenience Stores and Specialty Markets', TRUE, NOW(), NOW()),
        (5995, 'Pet Shops, Pet Foods, and Supplies Stores', TRUE, NOW(), NOW()),



        (763, 'Agricultural Co-operatives', FALSE, NOW(), NOW()),
        (780, 'Horticultural Services, Landscaping Services', FALSE, NOW(), NOW()),
        (1520, 'General Contractors-Residential and Commercial', FALSE, NOW(), NOW()),
        (1711, 'Air Conditioning Contractors – Sales and Installation, Heating Contractors – Sales, Service, Installation', FALSE, NOW(), NOW()),
        (1731, 'Electrical Contractors', FALSE, NOW(), NOW()),
        (1740, 'Insulation – Contractors, Masonry, Stonework Contractors, Plastering Contractors, Stonework and Masonry Contractors, Tile Settings Contractors', FALSE, NOW(), NOW()),
        (1750, 'Carpentry Contractors', FALSE, NOW(), NOW()),
        (1761, 'Roofing – Contractors, Sheet Metal Work – Contractors, Siding – Contractors', FALSE, NOW(), NOW()),
        (1771, 'Contractors – Concrete Work', FALSE, NOW(), NOW()),
        (1799, 'Contractors – Special Trade, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (2741, 'Miscellaneous Publishing and Printing', FALSE, NOW(), NOW()),
        (2791, 'Typesetting, Plate Making, & Related Services', FALSE, NOW(), NOW()),
        (2842, 'Specialty Cleaning, Polishing, and Sanitation Preparations', FALSE, NOW(), NOW()),
        (3000, 'UNITED AIRLINES', FALSE, NOW(), NOW()),
        (3001, 'AMERICAN AIRLINES', FALSE, NOW(), NOW()),
        (3002, 'PAN AMERICAN', FALSE, NOW(), NOW()),
        (3003, 'Airlines', FALSE, NOW(), NOW()),
        (3004, 'TRANS WORLD AIRLINES', FALSE, NOW(), NOW()),
        (3005, 'BRITISH AIRWAYS', FALSE, NOW(), NOW()),
        (3006, 'JAPAN AIRLINES', FALSE, NOW(), NOW()),
        (3007, 'AIR FRANCE', FALSE, NOW(), NOW()),
        (3008, 'LUFTHANSA', FALSE, NOW(), NOW()),
        (3009, 'AIR CANADA', FALSE, NOW(), NOW()),
        (3010, 'KLM (ROYAL DUTCH AIRLINES)', FALSE, NOW(), NOW()),
        (3011, 'AEORFLOT', FALSE, NOW(), NOW()),
        (3012, 'QANTAS', FALSE, NOW(), NOW()),
        (3013, 'ALITALIA', FALSE, NOW(), NOW()),
        (3014, 'SAUDIA ARABIAN AIRLINES', FALSE, NOW(), NOW()),
        (3015, 'SWISSAIR', FALSE, NOW(), NOW()),
        (3016, 'SAS', FALSE, NOW(), NOW()),
        (3017, 'SOUTH AFRICAN AIRWAYS', FALSE, NOW(), NOW()),
        (3018, 'VARIG (BRAZIL)', FALSE, NOW(), NOW()),
        (3019, 'Airlines', FALSE, NOW(), NOW()),
        (3020, 'AIR-INDIA', FALSE, NOW(), NOW()),
        (3021, 'AIR ALGERIE', FALSE, NOW(), NOW()),
        (3022, 'PHILIPPINE AIRLINES', FALSE, NOW(), NOW()),
        (3023, 'MEXICANA', FALSE, NOW(), NOW()),
        (3024, 'PAKISTAN INTERNATIONAL', FALSE, NOW(), NOW()),
        (3025, 'AIR NEW ZEALAND', FALSE, NOW(), NOW()),
        (3026, 'Airlines', FALSE, NOW(), NOW()),
        (3027, 'UTA/INTERAIR', FALSE, NOW(), NOW()),
        (3028, 'AIR MALTA', FALSE, NOW(), NOW()),
        (3029, 'SABENA', FALSE, NOW(), NOW()),
        (3030, 'AEROLINEAS ARGENTINAS', FALSE, NOW(), NOW()),
        (3031, 'OLYMPIC AIRWAYS', FALSE, NOW(), NOW()),
        (3032, 'EL AL', FALSE, NOW(), NOW()),
        (3033, 'ANSETT AIRLINES', FALSE, NOW(), NOW()),
        (3034, 'AUSTRAINLIAN AIRLINES', FALSE, NOW(), NOW()),
        (3035, 'TAP (PORTUGAL)', FALSE, NOW(), NOW()),
        (3036, 'VASP (BRAZIL)', FALSE, NOW(), NOW()),
        (3037, 'EGYPTAIR', FALSE, NOW(), NOW()),
        (3038, 'KUWAIT AIRLINES', FALSE, NOW(), NOW()),
        (3039, 'AVIANCA', FALSE, NOW(), NOW()),
        (3040, 'GULF AIR (BAHRAIN)', FALSE, NOW(), NOW()),
        (3041, 'BALKAN-BULGARIAN AIRLINES', FALSE, NOW(), NOW()),
        (3042, 'FINNAIR', FALSE, NOW(), NOW()),
        (3043, 'AER LINGUS', FALSE, NOW(), NOW()),
        (3044, 'AIR LANKA', FALSE, NOW(), NOW()),
        (3045, 'NIGERIA AIRWAYS', FALSE, NOW(), NOW()),
        (3046, 'CRUZEIRO DO SUL (BRAZIJ)', FALSE, NOW(), NOW()),
        (3047, 'THY (TURKEY)', FALSE, NOW(), NOW()),
        (3048, 'ROYAL AIR MAROC', FALSE, NOW(), NOW()),
        (3049, 'TUNIS AIR', FALSE, NOW(), NOW()),
        (3050, 'ICELANDAIR', FALSE, NOW(), NOW()),
        (3051, 'AUSTRIAN AIRLINES', FALSE, NOW(), NOW()),
        (3052, 'LANCHILE', FALSE, NOW(), NOW()),
        (3053, 'AVIACO (SPAIN)', FALSE, NOW(), NOW()),
        (3054, 'LADECO (CHILE)', FALSE, NOW(), NOW()),
        (3055, 'LAB (BOLIVIA)', FALSE, NOW(), NOW()),
        (3056, 'QUEBECAIRE', FALSE, NOW(), NOW()),
        (3057, 'EASTWEST AIRLINES (AUSTRALIA)', FALSE, NOW(), NOW()),
        (3058, 'DELTA', FALSE, NOW(), NOW()),
        (3059, 'Airlines', FALSE, NOW(), NOW()),
        (3060, 'NORTHWEST', FALSE, NOW(), NOW()),
        (3061, 'CONTINENTAL', FALSE, NOW(), NOW()),
        (3062, 'WESTERN', FALSE, NOW(), NOW()),
        (3063, 'US AIR', FALSE, NOW(), NOW()),
        (3064, 'Airlines', FALSE, NOW(), NOW()),
        (3065, 'AIRINTER', FALSE, NOW(), NOW()),
        (3066, 'SOUTHWEST', FALSE, NOW(), NOW()),
        (3067, 'Airlines', FALSE, NOW(), NOW()),
        (3068, 'Airlines', FALSE, NOW(), NOW()),
        (3069, 'SUN COUNTRY AIRLINES', FALSE, NOW(), NOW()),
        (3070, 'Airlines', FALSE, NOW(), NOW()),
        (3071, 'AIR BRITISH COLUBIA', FALSE, NOW(), NOW()),
        (3072, 'Airlines', FALSE, NOW(), NOW()),
        (3073, 'Airlines', FALSE, NOW(), NOW()),
        (3074, 'Airlines', FALSE, NOW(), NOW()),
        (3075, 'SINGAPORE AIRLINES', FALSE, NOW(), NOW()),
        (3076, 'AEROMEXICO', FALSE, NOW(), NOW()),
        (3077, 'THAI AIRWAYS', FALSE, NOW(), NOW()),
        (3078, 'CHINA AIRLINES', FALSE, NOW(), NOW()),
        (3079, 'Airlines', FALSE, NOW(), NOW()),
        (3080, 'Airlines', FALSE, NOW(), NOW()),
        (3081, 'NORDAIR', FALSE, NOW(), NOW()),
        (3082, 'KOREAN AIRLINES', FALSE, NOW(), NOW()),
        (3083, 'AIR AFRIGUE', FALSE, NOW(), NOW()),
        (3084, 'EVA AIRLINES', FALSE, NOW(), NOW()),
        (3085, 'MIDWEST EXPRESS AIRLINES, INC.', FALSE, NOW(), NOW()),
        (3086, 'Airlines', FALSE, NOW(), NOW()),
        (3087, 'METRO AIRLINES', FALSE, NOW(), NOW()),
        (3088, 'CROATIA AIRLINES', FALSE, NOW(), NOW()),
        (3089, 'TRANSAERO', FALSE, NOW(), NOW()),
        (3090, 'Airlines', FALSE, NOW(), NOW()),
        (3091, 'Airlines', FALSE, NOW(), NOW()),
        (3092, 'Airlines', FALSE, NOW(), NOW()),
        (3093, 'Airlines', FALSE, NOW(), NOW()),
        (3094, 'ZAMBIA AIRWAYS', FALSE, NOW(), NOW()),
        (3095, 'Airlines', FALSE, NOW(), NOW()),
        (3096, 'AIR ZIMBABWE', FALSE, NOW(), NOW()),
        (3097, 'Airlines', FALSE, NOW(), NOW()),
        (3098, 'Airlines', FALSE, NOW(), NOW()),
        (3099, 'CATHAY PACIFIC', FALSE, NOW(), NOW()),
        (3100, 'MALAYSIAN AIRLINE SYSTEM', FALSE, NOW(), NOW()),
        (3101, 'Airlines', FALSE, NOW(), NOW()),
        (3102, 'IBERIA', FALSE, NOW(), NOW()),
        (3103, 'GARUDA (INDONESIA)', FALSE, NOW(), NOW()),
        (3104, 'Airlines', FALSE, NOW(), NOW()),
        (3105, 'Airlines', FALSE, NOW(), NOW()),
        (3106, 'BRAATHENS S.A.F.E. (NORWAY)', FALSE, NOW(), NOW()),
        (3107, 'Airlines', FALSE, NOW(), NOW()),
        (3108, 'Airlines', FALSE, NOW(), NOW()),
        (3109, 'Airlines', FALSE, NOW(), NOW()),
        (3110, 'WINGS AIRWAYS', FALSE, NOW(), NOW()),
        (3111, 'BRITISH MIDLAND', FALSE, NOW(), NOW()),
        (3112, 'WINDWARD ISLAND', FALSE, NOW(), NOW()),
        (3113, 'Airlines', FALSE, NOW(), NOW()),
        (3114, 'Airlines', FALSE, NOW(), NOW()),
        (3115, 'Airlines', FALSE, NOW(), NOW()),
        (3116, 'Airlines', FALSE, NOW(), NOW()),
        (3117, 'VIASA', FALSE, NOW(), NOW()),
        (3118, 'VALLEY AIRLINES', FALSE, NOW(), NOW()),
        (3119, 'Airlines', FALSE, NOW(), NOW()),
        (3120, 'Airlines', FALSE, NOW(), NOW()),
        (3121, 'Airlines', FALSE, NOW(), NOW()),
        (3122, 'Airlines', FALSE, NOW(), NOW()),
        (3123, 'Airlines', FALSE, NOW(), NOW()),
        (3124, 'Airlines', FALSE, NOW(), NOW()),
        (3125, 'TAN', FALSE, NOW(), NOW()),
        (3126, 'TALAIR', FALSE, NOW(), NOW()),
        (3127, 'TACA INTERNATIONAL', FALSE, NOW(), NOW()),
        (3128, 'Airlines', FALSE, NOW(), NOW()),
        (3129, 'SURINAM AIRWAYS', FALSE, NOW(), NOW()),
        (3130, 'SUN WORLD INTERNATIONAL', FALSE, NOW(), NOW()),
        (3131, 'Airlines', FALSE, NOW(), NOW()),
        (3132, 'Airlines', FALSE, NOW(), NOW()),
        (3133, 'SUNBELT AIRLINES', FALSE, NOW(), NOW()),
        (3134, 'Airlines', FALSE, NOW(), NOW()),
        (3135, 'SUDAN AIRWAYS', FALSE, NOW(), NOW()),
        (3136, 'Airlines', FALSE, NOW(), NOW()),
        (3137, 'SINGLETON', FALSE, NOW(), NOW()),
        (3138, 'SIMMONS AIRLINES', FALSE, NOW(), NOW()),
        (3139, 'Airlines', FALSE, NOW(), NOW()),
        (3140, 'Airlines', FALSE, NOW(), NOW()),
        (3141, 'Airlines', FALSE, NOW(), NOW()),
        (3142, 'Airlines', FALSE, NOW(), NOW()),
        (3143, 'SCENIC AIRLINES', FALSE, NOW(), NOW()),
        (3144, 'VIRGIN ATLANTIC', FALSE, NOW(), NOW()),
        (3145, 'SAN JUAN AIRLINES', FALSE, NOW(), NOW()),
        (3146, 'LUXAIR', FALSE, NOW(), NOW()),
        (3147, 'Airlines', FALSE, NOW(), NOW()),
        (3148, 'Airlines', FALSE, NOW(), NOW()),
        (3149, 'Airlines', FALSE, NOW(), NOW()),
        (3150, 'Airlines', FALSE, NOW(), NOW()),
        (3151, 'AIR ZAIRE', FALSE, NOW(), NOW()),
        (3152, 'Airlines', FALSE, NOW(), NOW()),
        (3153, 'Airlines', FALSE, NOW(), NOW()),
        (3154, 'PRINCEVILLE', FALSE, NOW(), NOW()),
        (3155, 'Airlines', FALSE, NOW(), NOW()),
        (3156, 'Airlines', FALSE, NOW(), NOW()),
        (3157, 'Airlines', FALSE, NOW(), NOW()),
        (3158, 'Airlines', FALSE, NOW(), NOW()),
        (3159, 'PBA', FALSE, NOW(), NOW()),
        (3160, 'Airlines', FALSE, NOW(), NOW()),
        (3161, 'ALL NIPPON AIRWAYS', FALSE, NOW(), NOW()),
        (3162, 'Airlines', FALSE, NOW(), NOW()),
        (3163, 'Airlines', FALSE, NOW(), NOW()),
        (3164, 'NORONTAIR', FALSE, NOW(), NOW()),
        (3165, 'NEW YORK HELICOPTER', FALSE, NOW(), NOW()),
        (3166, 'Airlines', FALSE, NOW(), NOW()),
        (3167, 'Airlines', FALSE, NOW(), NOW()),
        (3168, 'Airlines', FALSE, NOW(), NOW()),
        (3169, 'Airlines', FALSE, NOW(), NOW()),
        (3170, 'NOUNT COOK', FALSE, NOW(), NOW()),
        (3171, 'CANADIAN AIRLINES INTERNATIONAL', FALSE, NOW(), NOW()),
        (3172, 'NATIONAIR', FALSE, NOW(), NOW()),
        (3173, 'Airlines', FALSE, NOW(), NOW()),
        (3174, 'Airlines', FALSE, NOW(), NOW()),
        (3175, 'Airlines', FALSE, NOW(), NOW()),
        (3176, 'METROFLIGHT AIRLINES', FALSE, NOW(), NOW()),
        (3177, 'Airlines', FALSE, NOW(), NOW()),
        (3178, 'MESA AIR', FALSE, NOW(), NOW()),
        (3179, 'Airlines', FALSE, NOW(), NOW()),
        (3180, 'Airlines', FALSE, NOW(), NOW()),
        (3181, 'MALEV', FALSE, NOW(), NOW()),
        (3182, 'LOT (POLAND)', FALSE, NOW(), NOW()),
        (3183, 'Airlines', FALSE, NOW(), NOW()),
        (3184, 'LIAT', FALSE, NOW(), NOW()),
        (3185, 'LAV (VENEZUELA)', FALSE, NOW(), NOW()),
        (3186, 'LAP (PARAGUAY)', FALSE, NOW(), NOW()),
        (3187, 'LACSA (COSTA RICA)', FALSE, NOW(), NOW()),
        (3188, 'Airlines', FALSE, NOW(), NOW()),
        (3189, 'Airlines', FALSE, NOW(), NOW()),
        (3190, 'JUGOSLAV AIR', FALSE, NOW(), NOW()),
        (3191, 'ISLAND AIRLINES', FALSE, NOW(), NOW()),
        (3192, 'IRAN AIR', FALSE, NOW(), NOW()),
        (3193, 'INDIAN AIRLINES', FALSE, NOW(), NOW()),
        (3194, 'Airlines', FALSE, NOW(), NOW()),
        (3195, 'Airlines', FALSE, NOW(), NOW()),
        (3196, 'HAWAIIAN AIR', FALSE, NOW(), NOW()),
        (3197, 'HAVASU AIRLINES', FALSE, NOW(), NOW()),
        (3198, 'Airlines', FALSE, NOW(), NOW()),
        (3199, 'Airlines', FALSE, NOW(), NOW()),
        (3200, 'FUYANA AIRWAYS', FALSE, NOW(), NOW()),
        (3201, 'Airlines', FALSE, NOW(), NOW()),
        (3202, 'Airlines', FALSE, NOW(), NOW()),
        (3203, 'GOLDEN PACIFIC AIR', FALSE, NOW(), NOW()),
        (3204, 'FREEDOM AIR', FALSE, NOW(), NOW()),
        (3205, 'Airlines', FALSE, NOW(), NOW()),
        (3206, 'Airlines', FALSE, NOW(), NOW()),
        (3207, 'Airlines', FALSE, NOW(), NOW()),
        (3208, 'Airlines', FALSE, NOW(), NOW()),
        (3209, 'Airlines', FALSE, NOW(), NOW()),
        (3210, 'Airlines', FALSE, NOW(), NOW()),
        (3211, 'Airlines', FALSE, NOW(), NOW()),
        (3212, 'DOMINICANA', FALSE, NOW(), NOW()),
        (3213, 'Airlines', FALSE, NOW(), NOW()),
        (3214, 'Airlines', FALSE, NOW(), NOW()),
        (3215, 'DAN AIR SERVICES', FALSE, NOW(), NOW()),
        (3216, 'CUMBERLAND AIRLINES', FALSE, NOW(), NOW()),
        (3217, 'CSA', FALSE, NOW(), NOW()),
        (3218, 'CROWN AIR', FALSE, NOW(), NOW()),
        (3219, 'COPA', FALSE, NOW(), NOW()),
        (3220, 'COMPANIA FAUCETT', FALSE, NOW(), NOW()),
        (3221, 'TRANSPORTES AEROS MILITARES ECCUATORANOS', FALSE, NOW(), NOW()),
        (3222, 'COMMAND AIRWAYS', FALSE, NOW(), NOW()),
        (3223, 'COMAIR', FALSE, NOW(), NOW()),
        (3224, 'Airlines', FALSE, NOW(), NOW()),
        (3225, 'Airlines', FALSE, NOW(), NOW()),
        (3226, 'Airlines', FALSE, NOW(), NOW()),
        (3227, 'Airlines', FALSE, NOW(), NOW()),
        (3228, 'CAYMAN AIRWAYS', FALSE, NOW(), NOW()),
        (3229, 'SAETA SOCIAEDAD ECUATORIANOS DE TRANSPORTES AEREOS', FALSE, NOW(), NOW()),
        (3230, 'Airlines', FALSE, NOW(), NOW()),
        (3231, 'SASHA SERVICIO AERO DE HONDURAS', FALSE, NOW(), NOW()),
        (3232, 'Airlines', FALSE, NOW(), NOW()),
        (3233, 'CAPITOL AIR', FALSE, NOW(), NOW()),
        (3234, 'BWIA', FALSE, NOW(), NOW()),
        (3235, 'BROKWAY AIR', FALSE, NOW(), NOW()),
        (3236, 'Airlines', FALSE, NOW(), NOW()),
        (3237, 'Airlines', FALSE, NOW(), NOW()),
        (3238, 'BEMIDJI AIRLINES', FALSE, NOW(), NOW()),
        (3239, 'BAR HARBOR AIRLINES', FALSE, NOW(), NOW()),
        (3240, 'BAHAMASAIR', FALSE, NOW(), NOW()),
        (3241, 'AVIATECA (GUATEMALA)', FALSE, NOW(), NOW()),
        (3242, 'AVENSA', FALSE, NOW(), NOW()),
        (3243, 'AUSTRIAN AIR SERVICE', FALSE, NOW(), NOW()),
        (3244, 'Airlines', FALSE, NOW(), NOW()),
        (3245, 'Airlines', FALSE, NOW(), NOW()),
        (3246, 'Airlines', FALSE, NOW(), NOW()),
        (3247, 'Airlines', FALSE, NOW(), NOW()),
        (3248, 'Airlines', FALSE, NOW(), NOW()),
        (3249, 'Airlines', FALSE, NOW(), NOW()),
        (3250, 'Airlines', FALSE, NOW(), NOW()),
        (3251, 'ALOHA AIRLINES', FALSE, NOW(), NOW()),
        (3252, 'ALM', FALSE, NOW(), NOW()),
        (3253, 'AMERICA WEST', FALSE, NOW(), NOW()),
        (3254, 'TRUMP AIRLINE', FALSE, NOW(), NOW()),
        (3255, 'Airlines', FALSE, NOW(), NOW()),
        (3256, 'ALASKA AIRLINES', FALSE, NOW(), NOW()),
        (3257, 'Airlines', FALSE, NOW(), NOW()),
        (3258, 'Airlines', FALSE, NOW(), NOW()),
        (3259, 'AMERICAN TRANS AIR', FALSE, NOW(), NOW()),
        (3260, 'Airlines', FALSE, NOW(), NOW()),
        (3261, 'AIR CHINA', FALSE, NOW(), NOW()),
        (3262, 'RENO AIR, INC.', FALSE, NOW(), NOW()),
        (3263, 'Airlines', FALSE, NOW(), NOW()),
        (3264, 'Airlines', FALSE, NOW(), NOW()),
        (3265, 'Airlines', FALSE, NOW(), NOW()),
        (3266, 'AIR SEYCHELLES', FALSE, NOW(), NOW()),
        (3267, 'AIR PANAMA', FALSE, NOW(), NOW()),
        (3268, 'Airlines', FALSE, NOW(), NOW()),
        (3269, 'Airlines', FALSE, NOW(), NOW()),
        (3270, 'Airlines', FALSE, NOW(), NOW()),
        (3271, 'Airlines', FALSE, NOW(), NOW()),
        (3272, 'Airlines', FALSE, NOW(), NOW()),
        (3273, 'Airlines', FALSE, NOW(), NOW()),
        (3274, 'Airlines', FALSE, NOW(), NOW()),
        (3275, 'Airlines', FALSE, NOW(), NOW()),
        (3276, 'Airlines', FALSE, NOW(), NOW()),
        (3277, 'Airlines', FALSE, NOW(), NOW()),
        (3278, 'Airlines', FALSE, NOW(), NOW()),
        (3279, 'Airlines', FALSE, NOW(), NOW()),
        (3280, 'AIR JAMAICA', FALSE, NOW(), NOW()),
        (3281, 'Airlines', FALSE, NOW(), NOW()),
        (3282, 'AIR DJIBOUTI', FALSE, NOW(), NOW()),
        (3283, 'Airlines', FALSE, NOW(), NOW()),
        (3284, 'AERO VIRGIN ISLANDS', FALSE, NOW(), NOW()),
        (3285, 'AERO PERU', FALSE, NOW(), NOW()),
        (3286, 'AEROLINEAS NICARAGUENSIS', FALSE, NOW(), NOW()),
        (3287, 'AERO COACH AVAIATION', FALSE, NOW(), NOW()),
        (3288, 'Airlines', FALSE, NOW(), NOW()),
        (3289, 'Airlines', FALSE, NOW(), NOW()),
        (3290, 'Airlines', FALSE, NOW(), NOW()),
        (3291, 'ARIANA AFGHAN', FALSE, NOW(), NOW()),
        (3292, 'CYPRUS AIRWAYS', FALSE, NOW(), NOW()),
        (3293, 'ECUATORIANA', FALSE, NOW(), NOW()),
        (3294, 'ETHIOPIAN AIRLINES', FALSE, NOW(), NOW()),
        (3295, 'KENYA AIRLINES', FALSE, NOW(), NOW()),
        (3296, 'Airlines', FALSE, NOW(), NOW()),
        (3297, 'Airlines', FALSE, NOW(), NOW()),
        (3298, 'AIR MAURITIUS', FALSE, NOW(), NOW()),
        (3299, 'WIDERO’S FLYVESELSKAP', FALSE, NOW(), NOW()),
        (3351, 'AFFILIATED AUTO RENTAL', FALSE, NOW(), NOW()),
        (3352, 'AMERICAN INTL RENT-A-CAR', FALSE, NOW(), NOW()),
        (3353, 'BROOKS RENT-A-CAR', FALSE, NOW(), NOW()),
        (3354, 'ACTION AUTO RENTAL', FALSE, NOW(), NOW()),
        (3355, 'Car Rental', FALSE, NOW(), NOW()),
        (3356, 'Car Rental', FALSE, NOW(), NOW()),
        (3357, 'HERTZ RENT-A-CAR', FALSE, NOW(), NOW()),
        (3358, 'Car Rental', FALSE, NOW(), NOW()),
        (3359, 'PAYLESS CAR RENTAL', FALSE, NOW(), NOW()),
        (3360, 'SNAPPY CAR RENTAL', FALSE, NOW(), NOW()),
        (3361, 'AIRWAYS RENT-A-CAR', FALSE, NOW(), NOW()),
        (3362, 'ALTRA AUTO RENTAL', FALSE, NOW(), NOW()),
        (3363, 'Car Rental', FALSE, NOW(), NOW()),
        (3364, 'AGENCY RENT-A-CAR', FALSE, NOW(), NOW()),
        (3365, 'Car Rental', FALSE, NOW(), NOW()),
        (3366, 'BUDGET RENT-A-CAR', FALSE, NOW(), NOW()),
        (3367, 'Car Rental', FALSE, NOW(), NOW()),
        (3368, 'HOLIDAY RENT-A-WRECK', FALSE, NOW(), NOW()),
        (3369, 'Car Rental', FALSE, NOW(), NOW()),
        (3370, 'RENT-A-WRECK', FALSE, NOW(), NOW()),
        (3371, 'Car Rental', FALSE, NOW(), NOW()),
        (3372, 'Car Rental', FALSE, NOW(), NOW()),
        (3373, 'Car Rental', FALSE, NOW(), NOW()),
        (3374, 'Car Rental', FALSE, NOW(), NOW()),
        (3375, 'Car Rental', FALSE, NOW(), NOW()),
        (3376, 'AJAX RENT-A-CAR', FALSE, NOW(), NOW()),
        (3377, 'Car Rental', FALSE, NOW(), NOW()),
        (3378, 'Car Rental', FALSE, NOW(), NOW()),
        (3379, 'Car Rental', FALSE, NOW(), NOW()),
        (3380, 'Car Rental', FALSE, NOW(), NOW()),
        (3381, 'EUROP CAR', FALSE, NOW(), NOW()),
        (3382, 'Car Rental', FALSE, NOW(), NOW()),
        (3383, 'Car Rental', FALSE, NOW(), NOW()),
        (3384, 'Car Rental', FALSE, NOW(), NOW()),
        (3385, 'TROPICAL RENT-A-CAR', FALSE, NOW(), NOW()),
        (3386, 'SHOWCASE RENTAL CARS', FALSE, NOW(), NOW()),
        (3387, 'ALAMO RENT-A-CAR', FALSE, NOW(), NOW()),
        (3388, 'Car Rental', FALSE, NOW(), NOW()),
        (3389, 'AVIS RENT-A-CAR', FALSE, NOW(), NOW()),
        (3390, 'DOLLAR RENT-A-CAR', FALSE, NOW(), NOW()),
        (3391, 'EUROPE BY CAR', FALSE, NOW(), NOW()),
        (3392, 'Car Rental', FALSE, NOW(), NOW()),
        (3393, 'NATIONAL CAR RENTAL', FALSE, NOW(), NOW()),
        (3394, 'KEMWELL GROUP RENT-A-CAR', FALSE, NOW(), NOW()),
        (3395, 'THRIFTY RENT-A-CAR', FALSE, NOW(), NOW()),
        (3396, 'TILDEN TENT-A-CAR', FALSE, NOW(), NOW()),
        (3397, 'Car Rental', FALSE, NOW(), NOW()),
        (3398, 'ECONO-CAR RENT-A-CAR', FALSE, NOW(), NOW()),
        (3399, 'Car Rental', FALSE, NOW(), NOW()),
        (3400, 'AUTO HOST COST CAR RENTALS', FALSE, NOW(), NOW()),
        (3401, 'Car Rental', FALSE, NOW(), NOW()),
        (3402, 'Car Rental', FALSE, NOW(), NOW()),
        (3403, 'Car Rental', FALSE, NOW(), NOW()),
        (3404, 'Car Rental', FALSE, NOW(), NOW()),
        (3405, 'ENTERPRISE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3406, 'Car Rental', FALSE, NOW(), NOW()),
        (3407, 'Car Rental', FALSE, NOW(), NOW()),
        (3408, 'Car Rental', FALSE, NOW(), NOW()),
        (3409, 'GENERAL RENT-A-CAR', FALSE, NOW(), NOW()),
        (3410, 'Car Rental', FALSE, NOW(), NOW()),
        (3411, 'Car Rental', FALSE, NOW(), NOW()),
        (3412, 'A-1 RENT-A-CAR', FALSE, NOW(), NOW()),
        (3413, 'Car Rental', FALSE, NOW(), NOW()),
        (3414, 'GODFREY NATL RENT-A-CAR', FALSE, NOW(), NOW()),
        (3415, 'Car Rental', FALSE, NOW(), NOW()),
        (3416, 'Car Rental', FALSE, NOW(), NOW()),
        (3417, 'Car Rental', FALSE, NOW(), NOW()),
        (3418, 'Car Rental', FALSE, NOW(), NOW()),
        (3419, 'ALPHA RENT-A-CAR', FALSE, NOW(), NOW()),
        (3420, 'ANSA INTL RENT-A-CAR', FALSE, NOW(), NOW()),
        (3421, 'ALLSTAE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3422, 'Car Rental', FALSE, NOW(), NOW()),
        (3423, 'AVCAR RENT-A-CAR', FALSE, NOW(), NOW()),
        (3424, 'Car Rental', FALSE, NOW(), NOW()),
        (3425, 'AUTOMATE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3426, 'Car Rental', FALSE, NOW(), NOW()),
        (3427, 'AVON RENT-A-CAR', FALSE, NOW(), NOW()),
        (3428, 'CAREY RENT-A-CAR', FALSE, NOW(), NOW()),
        (3429, 'INSURANCE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3430, 'MAJOR RENT-A-CAR', FALSE, NOW(), NOW()),
        (3431, 'REPLACEMENT RENT-A-CAR', FALSE, NOW(), NOW()),
        (3432, 'RESERVE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3433, 'UGLY DUCKLING RENT-A-CAR', FALSE, NOW(), NOW()),
        (3434, 'USA RENT-A-CAR', FALSE, NOW(), NOW()),
        (3435, 'VALUE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3436, 'AUTOHANSA RENT-A-CAR', FALSE, NOW(), NOW()),
        (3437, 'CITE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3438, 'INTERENT RENT-A-CAR', FALSE, NOW(), NOW()),
        (3439, 'MILLEVILLE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3440, 'VIA ROUTE RENT-A-CAR', FALSE, NOW(), NOW()),
        (3441, 'Car Rental', FALSE, NOW(), NOW()),
        (3501, 'HOLIDAY INNS, HOLIDAY INN EXPRESS', FALSE, NOW(), NOW()),
        (3502, 'BEST WESTERN HOTELS', FALSE, NOW(), NOW()),
        (3503, 'SHERATON HOTELS', FALSE, NOW(), NOW()),
        (3504, 'HILTON HOTELS', FALSE, NOW(), NOW()),
        (3505, 'FORTE HOTELS', FALSE, NOW(), NOW()),
        (3506, 'GOLDEN TULIP HOTELS', FALSE, NOW(), NOW()),
        (3507, 'FRIENDSHIP INNS', FALSE, NOW(), NOW()),
        (3508, 'QUALITY INNS, QUALITY SUITES', FALSE, NOW(), NOW()),
        (3509, 'MARRIOTT HOTELS', FALSE, NOW(), NOW()),
        (3510, 'DAYS INN, DAYSTOP', FALSE, NOW(), NOW()),
        (3511, 'ARABELLA HOTELS', FALSE, NOW(), NOW()),
        (3512, 'INTER-CONTINENTAL HOTELS', FALSE, NOW(), NOW()),
        (3513, 'WESTIN HOTELS', FALSE, NOW(), NOW()),
        (3514, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3515, 'RODEWAY INNS', FALSE, NOW(), NOW()),
        (3516, 'LA QUINTA MOTOR INNS', FALSE, NOW(), NOW()),
        (3517, 'AMERICANA HOTELS', FALSE, NOW(), NOW()),
        (3518, 'SOL HOTELS', FALSE, NOW(), NOW()),
        (3519, 'PULLMAN INTERNATIONAL HOTELS', FALSE, NOW(), NOW()),
        (3520, 'MERIDIEN HOTELS', FALSE, NOW(), NOW()),
        (3521, 'CREST HOTELS (see FORTE HOTELS)', FALSE, NOW(), NOW()),
        (3522, 'TOKYO HOTEL', FALSE, NOW(), NOW()),
        (3523, 'PENNSULA HOTEL', FALSE, NOW(), NOW()),
        (3524, 'WELCOMGROUP HOTELS', FALSE, NOW(), NOW()),
        (3525, 'DUNFEY HOTELS', FALSE, NOW(), NOW()),
        (3526, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3527, 'DOWNTOWNER-PASSPORT HOTEL', FALSE, NOW(), NOW()),
        (3528, 'RED LION HOTELS, RED LION INNS', FALSE, NOW(), NOW()),
        (3529, 'CP HOTELS', FALSE, NOW(), NOW()),
        (3530, 'RENAISSANCE HOTELS, STOUFFER HOTELS', FALSE, NOW(), NOW()),
        (3531, 'ASTIR HOTELS', FALSE, NOW(), NOW()),
        (3532, 'SUN ROUTE HOTELS', FALSE, NOW(), NOW()),
        (3533, 'HOTEL IBIS', FALSE, NOW(), NOW()),
        (3534, 'SOUTHERN PACIFIC HOTELS', FALSE, NOW(), NOW()),
        (3535, 'HILTON INTERNATIONAL', FALSE, NOW(), NOW()),
        (3536, 'AMFAC HOTELS', FALSE, NOW(), NOW()),
        (3537, 'ANA HOTEL', FALSE, NOW(), NOW()),
        (3538, 'CONCORDE HOTELS', FALSE, NOW(), NOW()),
        (3539, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3540, 'IBEROTEL HOTELS', FALSE, NOW(), NOW()),
        (3541, 'HOTEL OKURA', FALSE, NOW(), NOW()),
        (3542, 'ROYAL HOTELS', FALSE, NOW(), NOW()),
        (3543, 'FOUR SEASONS HOTELS', FALSE, NOW(), NOW()),
        (3544, 'CIGA HOTELS', FALSE, NOW(), NOW()),
        (3545, 'SHANGRI-LA INTERNATIONAL', FALSE, NOW(), NOW()),
        (3546, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3547, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3548, 'HOTELES MELIA', FALSE, NOW(), NOW()),
        (3549, 'AUBERGE DES GOVERNEURS', FALSE, NOW(), NOW()),
        (3550, 'REGAL 8 INNS', FALSE, NOW(), NOW()),
        (3551, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3552, 'COAST HOTELS', FALSE, NOW(), NOW()),
        (3553, 'PARK INNS INTERNATIONAL', FALSE, NOW(), NOW()),
        (3554, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3555, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3556, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3557, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3558, 'JOLLY HOTELS', FALSE, NOW(), NOW()),
        (3559, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3560, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3561, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3562, 'COMFORT INNS', FALSE, NOW(), NOW()),
        (3563, 'JOURNEY’S END MOTLS', FALSE, NOW(), NOW()),
        (3564, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3565, 'RELAX INNS', FALSE, NOW(), NOW()),
        (3566, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3567, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3568, 'LADBROKE HOTELS', FALSE, NOW(), NOW()),
        (3569, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3570, 'FORUM HOTELS', FALSE, NOW(), NOW()),
        (3571, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3572, 'MIYAKO HOTELS', FALSE, NOW(), NOW()),
        (3573, 'SANDMAN HOTELS', FALSE, NOW(), NOW()),
        (3574, 'VENTURE INNS', FALSE, NOW(), NOW()),
        (3575, 'VAGABOND HOTELS', FALSE, NOW(), NOW()),
        (3576, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3577, 'MANDARIN ORIENTAL HOTEL', FALSE, NOW(), NOW()),
        (3578, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3579, 'HOTEL MERCURE', FALSE, NOW(), NOW()),
        (3580, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3581, 'DELTA HOTEL', FALSE, NOW(), NOW()),
        (3582, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3583, 'SAS HOTELS', FALSE, NOW(), NOW()),
        (3584, 'PRINCESS HOTELS INTERNATIONAL', FALSE, NOW(), NOW()),
        (3585, 'HUNGAR HOTELS', FALSE, NOW(), NOW()),
        (3586, 'SOKOS HOTELS', FALSE, NOW(), NOW()),
        (3587, 'DORAL HOTELS', FALSE, NOW(), NOW()),
        (3588, 'HELMSLEY HOTELS', FALSE, NOW(), NOW()),
        (3589, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3590, 'FAIRMONT HOTELS', FALSE, NOW(), NOW()),
        (3591, 'SONESTA HOTELS', FALSE, NOW(), NOW()),
        (3592, 'OMNI HOTELS', FALSE, NOW(), NOW()),
        (3593, 'CUNARD HOTELS', FALSE, NOW(), NOW()),
        (3594, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3595, 'HOSPITALITY INTERNATIONAL', FALSE, NOW(), NOW()),
        (3596, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3597, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3598, 'REGENT INTERNATIONAL HOTELS', FALSE, NOW(), NOW()),
        (3599, 'PANNONIA HOTELS', FALSE, NOW(), NOW()),
        (3600, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3601, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3602, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3603, 'NOAH’S HOTELS', FALSE, NOW(), NOW()),
        (3604, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3605, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3606, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3607, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3608, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3609, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3610, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3611, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3612, 'MOVENPICK HOTELS', FALSE, NOW(), NOW()),
        (3613, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3614, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3615, 'TRAVELODGE', FALSE, NOW(), NOW()),
        (3616, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3617, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3618, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3619, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3620, 'TELFORD INTERNATIONAL', FALSE, NOW(), NOW()),
        (3621, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3622, 'MERLIN HOTELS', FALSE, NOW(), NOW()),
        (3623, 'DORINT HOTELS', FALSE, NOW(), NOW()),
        (3624, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3625, 'HOTLE UNIVERSALE', FALSE, NOW(), NOW()),
        (3626, 'PRINCE HOTELS', FALSE, NOW(), NOW()),
        (3627, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3628, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3629, 'DAN HOTELS', FALSE, NOW(), NOW()),
        (3630, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3631, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3632, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3633, 'RANK HOTELS', FALSE, NOW(), NOW()),
        (3634, 'SWISSOTEL', FALSE, NOW(), NOW()),
        (3635, 'RESO HOTELS', FALSE, NOW(), NOW()),
        (3636, 'SAROVA HOTELS', FALSE, NOW(), NOW()),
        (3637, 'RAMADA INNS, RAMADA LIMITED', FALSE, NOW(), NOW()),
        (3638, 'HO JO INN, HOWARD JOHNSON', FALSE, NOW(), NOW()),
        (3639, 'MOUNT CHARLOTTE THISTLE', FALSE, NOW(), NOW()),
        (3640, 'HYATT HOTEL', FALSE, NOW(), NOW()),
        (3641, 'SOFITEL HOTELS', FALSE, NOW(), NOW()),
        (3642, 'NOVOTEL HOTELS', FALSE, NOW(), NOW()),
        (3643, 'STEIGENBERGER HOTELS', FALSE, NOW(), NOW()),
        (3644, 'ECONO LODGES', FALSE, NOW(), NOW()),
        (3645, 'QUEENS MOAT HOUSES', FALSE, NOW(), NOW()),
        (3646, 'SWALLOW HOTELS', FALSE, NOW(), NOW()),
        (3647, 'HUSA HOTELS', FALSE, NOW(), NOW()),
        (3648, 'DE VERE HOTELS', FALSE, NOW(), NOW()),
        (3649, 'RADISSON HOTELS', FALSE, NOW(), NOW()),
        (3650, 'RED ROOK INNS', FALSE, NOW(), NOW()),
        (3651, 'IMPERIAL LONDON HOTEL', FALSE, NOW(), NOW()),
        (3652, 'EMBASSY HOTELS', FALSE, NOW(), NOW()),
        (3653, 'PENTA HOTELS', FALSE, NOW(), NOW()),
        (3654, 'LOEWS HOTELS', FALSE, NOW(), NOW()),
        (3655, 'SCANDIC HOTELS', FALSE, NOW(), NOW()),
        (3656, 'SARA HOTELS', FALSE, NOW(), NOW()),
        (3657, 'OBEROI HOTELS', FALSE, NOW(), NOW()),
        (3658, 'OTANI HOTELS', FALSE, NOW(), NOW()),
        (3659, 'TAJ HOTELS INTERNATIONAL', FALSE, NOW(), NOW()),
        (3660, 'KNIGHTS INNS', FALSE, NOW(), NOW()),
        (3661, 'METROPOLE HOTELS', FALSE, NOW(), NOW()),
        (3662, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3663, 'HOTELES EL PRESIDENTS', FALSE, NOW(), NOW()),
        (3664, 'FLAG INN', FALSE, NOW(), NOW()),
        (3665, 'HAMPTON INNS', FALSE, NOW(), NOW()),
        (3666, 'STAKIS HOTELS', FALSE, NOW(), NOW()),
        (3667, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3668, 'MARITIM HOTELS', FALSE, NOW(), NOW()),
        (3669, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3670, 'ARCARD HOTELS', FALSE, NOW(), NOW()),
        (3671, 'ARCTIA HOTELS', FALSE, NOW(), NOW()),
        (3672, 'CAMPANIEL HOTELS', FALSE, NOW(), NOW()),
        (3673, 'IBUSZ HOTELS', FALSE, NOW(), NOW()),
        (3674, 'RANTASIPI HOTELS', FALSE, NOW(), NOW()),
        (3675, 'INTERHOTEL CEDOK', FALSE, NOW(), NOW()),
        (3676, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3677, 'CLIMAT DE FRANCE HOTELS', FALSE, NOW(), NOW()),
        (3678, 'CUMULUS HOTELS', FALSE, NOW(), NOW()),
        (3679, 'DANUBIUS HOTEL', FALSE, NOW(), NOW()),
        (3680, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3681, 'ADAMS MARK HOTELS', FALSE, NOW(), NOW()),
        (3682, 'ALLSTAR INNS', FALSE, NOW(), NOW()),
        (3683, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3684, 'BUDGET HOST INNS', FALSE, NOW(), NOW()),
        (3685, 'BUDGETEL HOTELS', FALSE, NOW(), NOW()),
        (3686, 'SUISSE CHALETS', FALSE, NOW(), NOW()),
        (3687, 'CLARION HOTELS', FALSE, NOW(), NOW()),
        (3688, 'COMPRI HOTELS', FALSE, NOW(), NOW()),
        (3689, 'CONSORT HOTELS', FALSE, NOW(), NOW()),
        (3690, 'COURTYARD BY MARRIOTT', FALSE, NOW(), NOW()),
        (3691, 'DILLION INNS', FALSE, NOW(), NOW()),
        (3692, 'DOUBLETREE HOTELS', FALSE, NOW(), NOW()),
        (3693, 'DRURY INNS', FALSE, NOW(), NOW()),
        (3694, 'ECONOMY INNS OF AMERICA', FALSE, NOW(), NOW()),
        (3695, 'EMBASSY SUITES', FALSE, NOW(), NOW()),
        (3696, 'EXEL INNS', FALSE, NOW(), NOW()),
        (3697, 'FARFIELD HOTELS', FALSE, NOW(), NOW()),
        (3698, 'HARLEY HOTELS', FALSE, NOW(), NOW()),
        (3699, 'MIDWAY MOTOR LODGE', FALSE, NOW(), NOW()),
        (3700, 'MOTEL 6', FALSE, NOW(), NOW()),
        (3701, 'GUEST QUARTERS (Formally PICKETT SUITE HOTELS)', FALSE, NOW(), NOW()),
        (3702, 'THE REGISTRY HOTELS', FALSE, NOW(), NOW()),
        (3703, 'RESIDENCE INNS', FALSE, NOW(), NOW()),
        (3704, 'ROYCE HOTELS', FALSE, NOW(), NOW()),
        (3705, 'SANDMAN INNS', FALSE, NOW(), NOW()),
        (3706, 'SHILO INNS', FALSE, NOW(), NOW()),
        (3707, 'SHONEY’S INNS', FALSE, NOW(), NOW()),
        (3708, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3709, 'SUPER8 MOTELS', FALSE, NOW(), NOW()),
        (3710, 'THE RITZ CARLTON HOTELS', FALSE, NOW(), NOW()),
        (3711, 'FLAG INNS (AUSRALIA)', FALSE, NOW(), NOW()),
        (3712, 'GOLDEN CHAIN HOTEL', FALSE, NOW(), NOW()),
        (3713, 'QUALITY PACIFIC HOTEL', FALSE, NOW(), NOW()),
        (3714, 'FOUR SEASONS HOTEL (AUSTRALIA)', FALSE, NOW(), NOW()),
        (3715, 'FARIFIELD INN', FALSE, NOW(), NOW()),
        (3716, 'CARLTON HOTELS', FALSE, NOW(), NOW()),
        (3717, 'CITY LODGE HOTELS', FALSE, NOW(), NOW()),
        (3718, 'KAROS HOTELS', FALSE, NOW(), NOW()),
        (3719, 'PROTEA HOTELS', FALSE, NOW(), NOW()),
        (3720, 'SOUTHERN SUN HOTELS', FALSE, NOW(), NOW()),
        (3721, 'HILTON CONRAD', FALSE, NOW(), NOW()),
        (3722, 'WYNDHAM HOTEL AND RESORTS', FALSE, NOW(), NOW()),
        (3723, 'RICA HOTELS', FALSE, NOW(), NOW()),
        (3724, 'INER NOR HOTELS', FALSE, NOW(), NOW()),
        (3725, 'SEAINES PLANATION', FALSE, NOW(), NOW()),
        (3726, 'RIO SUITES', FALSE, NOW(), NOW()),
        (3727, 'BROADMOOR HOTEL', FALSE, NOW(), NOW()),
        (3728, 'BALLY’S HOTEL AND CASINO', FALSE, NOW(), NOW()),
        (3729, 'JOHN ASCUAGA’S NUGGET', FALSE, NOW(), NOW()),
        (3730, 'MGM GRAND HOTEL', FALSE, NOW(), NOW()),
        (3731, 'HARRAH’S HOTELS AND CASINOS', FALSE, NOW(), NOW()),
        (3732, 'OPRYLAND HOTEL', FALSE, NOW(), NOW()),
        (3733, 'BOCA RATON RESORT', FALSE, NOW(), NOW()),
        (3734, 'HARVEY/BRISTOL HOTELS', FALSE, NOW(), NOW()),
        (3735, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3736, 'COLORADO BELLE/EDGEWATER RESORT', FALSE, NOW(), NOW()),
        (3737, 'RIVIERA HOTEL AND CASINO', FALSE, NOW(), NOW()),
        (3738, 'TROPICANA RESORT AND CASINO', FALSE, NOW(), NOW()),
        (3739, 'WOODSIDE HOTELS AND RESORTS', FALSE, NOW(), NOW()),
        (3740, 'TOWNPLACE SUITES', FALSE, NOW(), NOW()),
        (3741, 'MILLENIUM BROADWAY HOTEL', FALSE, NOW(), NOW()),
        (3742, 'CLUB MED', FALSE, NOW(), NOW()),
        (3743, 'BILTMORE HOTEL AND SUITES', FALSE, NOW(), NOW()),
        (3744, 'CAREFREE RESORTS', FALSE, NOW(), NOW()),
        (3745, 'ST. REGIS HOTEL', FALSE, NOW(), NOW()),
        (3746, 'THE ELIOT HOTEL', FALSE, NOW(), NOW()),
        (3747, 'CLUBCORP/CLUB RESORTS', FALSE, NOW(), NOW()),
        (3748, 'WELESLEY INNS', FALSE, NOW(), NOW()),
        (3749, 'THE BEVERLY HILLS HOTEL', FALSE, NOW(), NOW()),
        (3750, 'CROWNE PLAZA HOTELS', FALSE, NOW(), NOW()),
        (3751, 'HOMEWOOD SUITES', FALSE, NOW(), NOW()),
        (3752, 'PEABODY HOTELS', FALSE, NOW(), NOW()),
        (3753, 'GREENBRIAH RESORTS', FALSE, NOW(), NOW()),
        (3754, 'AMELIA ISLAND PLANATION', FALSE, NOW(), NOW()),
        (3755, 'THE HOMESTEAD', FALSE, NOW(), NOW()),
        (3756, 'SOUTH SEAS RESORTS', FALSE, NOW(), NOW()),
        (3757, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3758, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3759, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3760, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3761, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3762, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3763, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3764, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3765, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3766, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3767, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3768, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3769, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3770, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3771, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3772, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3773, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3774, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3775, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3776, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3777, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3778, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3779, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3780, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3781, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3782, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3783, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3784, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3785, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3786, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3787, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3788, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3789, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3790, 'Hotels/Motels/Inns/Resorts', FALSE, NOW(), NOW()),
        (3816, 'Home2Suites', FALSE, NOW(), NOW()),
        (3835, '* MASTERS ECONOMY INNS', FALSE, NOW(), NOW()),
        (4011, 'Railroads', FALSE, NOW(), NOW()),
        (4111, 'Local/Suburban Commuter Passenger Transportation – Railroads, Feries, Local Water Transportation.', FALSE, NOW(), NOW()),
        (4112, 'Passenger Railways', FALSE, NOW(), NOW()),
        (4119, 'Ambulance Services', FALSE, NOW(), NOW()),
        (4121, 'Taxicabs and Limousines', FALSE, NOW(), NOW()),
        (4131, 'Bus Lines, Including Charters, Tour Buses', FALSE, NOW(), NOW()),
        (4214, 'Motor Freight Carriers, Moving and Storage Companies, Trucking – Local/Long Distance, Delivery Services – Local', FALSE, NOW(), NOW()),
        (4215, 'Courier Services – Air or Ground, Freight forwarders', FALSE, NOW(), NOW()),
        (4225, 'Public warehousing, Storage', FALSE, NOW(), NOW()),
        (4411, 'Cruise and Steamship Lines', FALSE, NOW(), NOW()),
        (4457, 'Boat Rentals and Leases', FALSE, NOW(), NOW()),
        (4468, 'Marinas, Marine Service, and Supplies', FALSE, NOW(), NOW()),
        (4511, 'Airlines, Air Carriers ( not listed elsewhere)', FALSE, NOW(), NOW()),
        (4582, 'Airports, Airport Terminals, Flying Fields', FALSE, NOW(), NOW()),
        (4722, 'Travel Agencies and Tour Operations', FALSE, NOW(), NOW()),
        (4723, 'Package Tour Operators (For use in Germany only)', FALSE, NOW(), NOW()),
        (4784, 'Toll and Bridge Fees', FALSE, NOW(), NOW()),
        (4789, 'Transportation Services, Not elsewhere classified)', FALSE, NOW(), NOW()),
        (4812, 'Telecommunications Equipment including telephone sales', FALSE, NOW(), NOW()),
        (4814, 'Fax services, Telecommunication Services', FALSE, NOW(), NOW()),
        (4815, 'VisaPhone', FALSE, NOW(), NOW()),
        (4816, 'Computer Network Services', FALSE, NOW(), NOW()),
        (4821, 'Telegraph services', FALSE, NOW(), NOW()),
        (4829, 'Money Orders – Wire Transfer', FALSE, NOW(), NOW()),
        (4899, 'Cable and other pay television (previously Cable Services)', FALSE, NOW(), NOW()),
        (5013, 'Motor vehicle supplies and new parts', FALSE, NOW(), NOW()),
        (5021, 'Office and Commercial Furniture', FALSE, NOW(), NOW()),
        (5039, 'Construction Materials, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5044, 'Office, Photographic, Photocopy, and Microfilm Equipment', FALSE, NOW(), NOW()),
        (5045, 'Computers, Computer Peripheral Equipment, Software', FALSE, NOW(), NOW()),
        (5046, 'Commercial Equipment, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5047, 'Medical, Dental Ophthalmic, Hospital Equipment and Supplies', FALSE, NOW(), NOW()),
        (5051, 'Metal Service Centers and Offices', FALSE, NOW(), NOW()),
        (5065, 'Electrical Parts and Equipment', FALSE, NOW(), NOW()),
        (5072, 'Hardware Equipment and Supplies', FALSE, NOW(), NOW()),
        (5074, 'Plumbing and Heating Equipment and Supplies', FALSE, NOW(), NOW()),
        (5085, 'Industrial Supplies, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5094, 'Precious Stones and Metals, Watches and Jewelry', FALSE, NOW(), NOW()),
        (5099, 'Durable Goods, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5111, 'Stationery, Office Supplies, Printing, and Writing Paper', FALSE, NOW(), NOW()),
        (5122, 'Drugs, Drug Proprietors, and Druggist’s Sundries', FALSE, NOW(), NOW()),
        (5131, 'Piece Goods, Notions, and Other Dry Goods', FALSE, NOW(), NOW()),
        (5137, 'Men’s Women’s and Children’s Uniforms and Commercial Clothing', FALSE, NOW(), NOW()),
        (5139, 'Commercial Footwear', FALSE, NOW(), NOW()),
        (5169, 'Chemicals and Allied Products, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5172, 'Petroleum and Petroleum Products', FALSE, NOW(), NOW()),
        (5192, 'Books, Periodicals, and Newspapers', FALSE, NOW(), NOW()),
        (5193, 'Florists’ Supplies, Nursery Stock and Flowers', FALSE, NOW(), NOW()),
        (5198, 'Paints, Varnishes, and Supplies', FALSE, NOW(), NOW()),
        (5199, 'Non-durable Goods, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5200, 'Home Supply Warehouse Stores', FALSE, NOW(), NOW()),
        (5211, 'Lumber and Building Materials Stores', FALSE, NOW(), NOW()),
        (5231, 'Glass, Paint, and Wallpaper Stores', FALSE, NOW(), NOW()),
        (5251, 'Hardware Stores', FALSE, NOW(), NOW()),
        (5261, 'Nurseries – Lawn and Garden Supply Store', FALSE, NOW(), NOW()),
        (5271, 'Mobile Home Dealers', FALSE, NOW(), NOW()),
        (5309, 'Duty Free Store', FALSE, NOW(), NOW()),
        (5310, 'Discount Stores', FALSE, NOW(), NOW()),
        (5311, 'Department Stores', FALSE, NOW(), NOW()),
        (5331, 'Variety Stores', FALSE, NOW(), NOW()),
        (5422, 'Meat Provisioners – Freezer and Locker', FALSE, NOW(), NOW()),
        (5441, 'Candy, Nut, and Confectionery Stores', FALSE, NOW(), NOW()),
        (5451, 'Dairy Products Stores', FALSE, NOW(), NOW()),
        (5462, 'Bakeries', FALSE, NOW(), NOW()),
        (5511, 'Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing', FALSE, NOW(), NOW()),
        (5521, 'Automobile and Truck Dealers (Used Only)', FALSE, NOW(), NOW()),
        (5531, 'Automobile Supply Stores', FALSE, NOW(), NOW()),
        (5532, 'Automotive Tire Stores', FALSE, NOW(), NOW()),
        (5533, 'Automotive Parts, Accessories Stores', FALSE, NOW(), NOW()),
        (5541, 'Service Stations ( with or without ancillary services)', FALSE, NOW(), NOW()),
        (5551, 'Boat Dealers', FALSE, NOW(), NOW()),
        (5561, 'Recreational and Utility Trailers, Camp Dealers', FALSE, NOW(), NOW()),
        (5571, 'Motorcycle Dealers', FALSE, NOW(), NOW()),
        (5592, 'Motor Home Dealers', FALSE, NOW(), NOW()),
        (5598, 'Snowmobile Dealers', FALSE, NOW(), NOW()),
        (5599, 'Miscellaneous Auto Dealers ', FALSE, NOW(), NOW()),
        (5611, 'Men’s and Boy’s Clothing and Accessories Stores', FALSE, NOW(), NOW()),
        (5621, 'Women’s Ready-to-Wear Stores', FALSE, NOW(), NOW()),
        (5631, 'Women’s Accessory and Specialty Shops', FALSE, NOW(), NOW()),
        (5641, 'Children’s and Infant’s Wear Stores', FALSE, NOW(), NOW()),
        (5651, 'Family Clothing Stores', FALSE, NOW(), NOW()),
        (5655, 'Sports Apparel, Riding Apparel Stores', FALSE, NOW(), NOW()),
        (5661, 'Shoe Stores', FALSE, NOW(), NOW()),
        (5681, 'Furriers and Fur Shops', FALSE, NOW(), NOW()),
        (5691, 'Men’s and Women’s Clothing Stores', FALSE, NOW(), NOW()),
        (5697, 'Tailors, Seamstress, Mending, and Alterations', FALSE, NOW(), NOW()),
        (5698, 'Wig and Toupee Stores', FALSE, NOW(), NOW()),
        (5699, 'Miscellaneous Apparel and Accessory Shops', FALSE, NOW(), NOW()),
        (5712, 'Furniture, Home Furnishings, and Equipment Stores, ExceptAppliances', FALSE, NOW(), NOW()),
        (5713, 'Floor Covering Stores', FALSE, NOW(), NOW()),
        (5714, 'Drapery, Window Covering and Upholstery Stores', FALSE, NOW(), NOW()),
        (5718, 'Fireplace, Fireplace Screens, and Accessories Stores', FALSE, NOW(), NOW()),
        (5719, 'Miscellaneous Home Furnishing Specialty Stores', FALSE, NOW(), NOW()),
        (5722, 'Household Appliance Stores', FALSE, NOW(), NOW()),
        (5733, 'Music Stores, Musical Instruments, Piano Sheet Music', FALSE, NOW(), NOW()),
        (5734, 'Computer Software Stores', FALSE, NOW(), NOW()),
        (5735, 'Record Shops', FALSE, NOW(), NOW()),
        (5811, 'Caterers', FALSE, NOW(), NOW()),
        (5815, 'Digital Goods: Media, Books, Movies, Music', FALSE, NOW(), NOW()),
        (5816, 'Digital Goods: Games', FALSE, NOW(), NOW()),
        (5817, 'Digital Goods: Applications (Excludes Games)', FALSE, NOW(), NOW()),
        (5818, 'Digital Goods: Large Digital Goods Merchant', FALSE, NOW(), NOW()),
        (5832, 'Antique Shops – Sales, Repairs, and Restoration Services', FALSE, NOW(), NOW()),
        (5921, 'Package Stores – Beer, Wine, and Liquor', FALSE, NOW(), NOW()),
        (5931, 'Used Merchandise and Secondhand Stores', FALSE, NOW(), NOW()),
        (5932, 'Antique Shops', FALSE, NOW(), NOW()),
        (5933, 'Pawn Shops and Salvage Yards', FALSE, NOW(), NOW()),
        (5935, 'Wrecking and Salvage Yards', FALSE, NOW(), NOW()),
        (5937, 'Antique Reproductions', FALSE, NOW(), NOW()),
        (5940, 'Bicycle Shops – Sales and Service', FALSE, NOW(), NOW()),
        (5941, 'Sporting Goods Stores', FALSE, NOW(), NOW()),
        (5942, 'Book Stores', FALSE, NOW(), NOW()),
        (5943, 'Stationery Stores, Office and School Supply Stores', FALSE, NOW(), NOW()),
        (5944, 'Watch, Clock, Jewelry, and Silverware Stores', FALSE, NOW(), NOW()),
        (5946, 'Camera and Photographic Supply Stores', FALSE, NOW(), NOW()),
        (5947, 'Card Shops, Gift, Novelty, and Souvenir Shops', FALSE, NOW(), NOW()),
        (5948, 'Leather Goods Stores', FALSE, NOW(), NOW()),
        (5949, 'Sewing, Needle, Fabric, and Price Goods Stores', FALSE, NOW(), NOW()),
        (5950, 'Glassware/Crystal Stores', FALSE, NOW(), NOW()),
        (5960, 'Direct Marketing- Insurance Service', FALSE, NOW(), NOW()),
        (5961, 'Mail Order Houses Including Catalog Order Stores, Book/Record Clubs (No longer permitted for U.S. original presentments)', FALSE, NOW(), NOW()),
        (5962, 'Direct Marketing – Travel Related Arrangements Services', FALSE, NOW(), NOW()),
        (5963, 'Door-to-Door Sales', FALSE, NOW(), NOW()),
        (5964, 'Direct Marketing – Catalog Merchant', FALSE, NOW(), NOW()),
        (5965, 'Direct Marketing – Catalog and Catalog and Retail Merchant', FALSE, NOW(), NOW()),
        (5966, 'Direct Marketing- Outbound Telemarketing Merchant', FALSE, NOW(), NOW()),
        (5967, 'Direct Marketing – Inbound Teleservices Merchant', FALSE, NOW(), NOW()),
        (5968, 'Direct Marketing – Continuity/Subscription Merchant', FALSE, NOW(), NOW()),
        (5969, 'Direct Marketing – Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (5970, 'Artist’s Supply and Craft Shops', FALSE, NOW(), NOW()),
        (5971, 'Art Dealers and Galleries', FALSE, NOW(), NOW()),
        (5972, 'Stamp and Coin Stores – Philatelic and Numismatic Supplies', FALSE, NOW(), NOW()),
        (5973, 'Religious Goods Stores', FALSE, NOW(), NOW()),
        (5975, 'Hearing Aids – Sales, Service, and Supply Stores', FALSE, NOW(), NOW()),
        (5976, 'Orthopedic Goods Prosthetic Devices', FALSE, NOW(), NOW()),
        (5977, 'Cosmetic Stores', FALSE, NOW(), NOW()),
        (5978, 'Typewriter Stores – Sales, Rental, Service', FALSE, NOW(), NOW()),
        (5983, 'Fuel – Fuel Oil, Wood, Coal, Liquefied Petroleum', FALSE, NOW(), NOW()),
        (5992, 'Florists', FALSE, NOW(), NOW()),
        (5993, 'Cigar Stores and Stands', FALSE, NOW(), NOW()),
        (5994, 'News Dealers and Newsstands', FALSE, NOW(), NOW()),
        (5996, 'Swimming Pools – Sales, Service, and Supplies', FALSE, NOW(), NOW()),
        (5997, 'Electric Razor Stores – Sales and Service', FALSE, NOW(), NOW()),
        (5998, 'Tent and Awning Shops', FALSE, NOW(), NOW()),
        (5999, 'Miscellaneous and Specialty Retail Stores', FALSE, NOW(), NOW()),
        (6010, 'Financial Institutions – Manual Cash Disbursements', FALSE, NOW(), NOW()),
        (6011, 'Financial Institutions – Manual Cash Disbursements', FALSE, NOW(), NOW()),
        (6012, 'Financial Institutions – Merchandise and Services', FALSE, NOW(), NOW()),
        (6051, 'Non-Financial Institutions – Foreign Currency, Money Orders (not wire transfer) and Travelers Cheques', FALSE, NOW(), NOW()),
        (6211, 'Security Brokers/Dealers', FALSE, NOW(), NOW()),
        (6300, 'Insurance Sales, Underwriting, and Premiums', FALSE, NOW(), NOW()),
        (6381, 'Insurance Premiums, (no longer valid for first presentment work)', FALSE, NOW(), NOW()),
        (6399, 'Insurance, Not Elsewhere Classified ( no longer valid forfirst presentment work)', FALSE, NOW(), NOW()),
        (6513, 'Real Estate Agents and Managers - Rentals', FALSE, NOW(), NOW()),
        (7011, 'Lodging – Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)', FALSE, NOW(), NOW()),
        (7012, 'Timeshares', FALSE, NOW(), NOW()),
        (7032, 'Sporting and Recreational Camps', FALSE, NOW(), NOW()),
        (7033, 'Trailer Parks and Camp Grounds', FALSE, NOW(), NOW()),
        (7210, 'Laundry, Cleaning, and Garment Services', FALSE, NOW(), NOW()),
        (7211, 'Laundry – Family and Commercial', FALSE, NOW(), NOW()),
        (7216, 'Dry Cleaners', FALSE, NOW(), NOW()),
        (7217, 'Carpet and Upholstery Cleaning', FALSE, NOW(), NOW()),
        (7221, 'Photographic Studios', FALSE, NOW(), NOW()),
        (7251, 'Shop Repair Shops and Shoe Shine Parlors, and Hat Cleaning Shops', FALSE, NOW(), NOW()),
        (7261, 'Funeral Service and Crematories', FALSE, NOW(), NOW()),
        (7273, 'Dating and Escort Services', FALSE, NOW(), NOW()),
        (7276, 'Tax Preparation Service', FALSE, NOW(), NOW()),
        (7277, 'Counseling Service – Debt, Marriage, Personal', FALSE, NOW(), NOW()),
        (7278, 'Buying/Shopping Services, Clubs', FALSE, NOW(), NOW()),
        (7296, 'Clothing Rental – Costumes, Formal Wear, Uniforms', FALSE, NOW(), NOW()),
        (7297, 'Massage Parlors', FALSE, NOW(), NOW()),
        (7298, 'Health and Beauty Shops', FALSE, NOW(), NOW()),
        (7299, 'Miscellaneous Personal Services ( not elsewhere classifies)', FALSE, NOW(), NOW()),
        (7311, 'Advertising Services', FALSE, NOW(), NOW()),
        (7321, 'Consumer Credit Reporting Agencies', FALSE, NOW(), NOW()),
        (7332, 'Blueprinting and Photocopying Services', FALSE, NOW(), NOW()),
        (7333, 'Commercial Photography, Art and Graphics', FALSE, NOW(), NOW()),
        (7338, 'Quick Copy, Reproduction and Blueprinting Services', FALSE, NOW(), NOW()),
        (7339, 'Stenographic and Secretarial Support Services', FALSE, NOW(), NOW()),
        (7342, 'Exterminating and Disinfecting Services', FALSE, NOW(), NOW()),
        (7349, 'Cleaning and Maintenance, Janitorial Services', FALSE, NOW(), NOW()),
        (7361, 'Employment Agencies, Temporary Help Services', FALSE, NOW(), NOW()),
        (7372, 'Computer Programming, Integrated Systems Design and Data Processing Services', FALSE, NOW(), NOW()),
        (7375, 'Information Retrieval Services', FALSE, NOW(), NOW()),
        (7379, 'Computer Maintenance and Repair Services, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (7392, 'Management, Consulting, and Public Relations Services', FALSE, NOW(), NOW()),
        (7393, 'Protective and Security Services – Including Armored Carsand Guard Dogs', FALSE, NOW(), NOW()),
        (7394, 'Equipment Rental and Leasing Services, Tool Rental, Furniture Rental, and Appliance Rental', FALSE, NOW(), NOW()),
        (7395, 'Photofinishing Laboratories, Photo Developing', FALSE, NOW(), NOW()),
        (7399, 'Business Services, Not Elsewhere Classified', FALSE, NOW(), NOW()),
        (7511, 'Truck Stop', FALSE, NOW(), NOW()),
        (7512, 'Car Rental Companies ( Not Listed Below)', FALSE, NOW(), NOW()),
        (7513, 'Truck and Utility Trailer Rentals', FALSE, NOW(), NOW()),
        (7519, 'Motor Home and Recreational Vehicle Rentals', FALSE, NOW(), NOW()),
        (7523, 'Automobile Parking Lots and Garages', FALSE, NOW(), NOW()),
        (7531, 'Automotive Body Repair Shops', FALSE, NOW(), NOW()),
        (7534, 'Tire Re-treading and Repair Shops', FALSE, NOW(), NOW()),
        (7535, 'Paint Shops – Automotive', FALSE, NOW(), NOW()),
        (7538, 'Automotive Service Shops', FALSE, NOW(), NOW()),
        (7542, 'Car Washes', FALSE, NOW(), NOW()),
        (7549, 'Towing Services', FALSE, NOW(), NOW()),
        (7622, 'Radio Repair Shops', FALSE, NOW(), NOW()),
        (7623, 'Air Conditioning and Refrigeration Repair Shops', FALSE, NOW(), NOW()),
        (7629, 'Electrical And Small Appliance Repair Shops', FALSE, NOW(), NOW()),
        (7631, 'Watch, Clock, and Jewelry Repair', FALSE, NOW(), NOW()),
        (7641, 'Furniture, Furniture Repair, and Furniture Refinishing', FALSE, NOW(), NOW()),
        (7692, 'Welding Repair', FALSE, NOW(), NOW()),
        (7699, 'Repair Shops and Related Services –Miscellaneous', FALSE, NOW(), NOW()),
        (7800, 'Government-Owned Lotteries', FALSE, NOW(), NOW()),
        (7801, 'Government-Licensed On-Line Casinos (On-Line Gambling)', FALSE, NOW(), NOW()),
        (7802, 'Government-Licensed Horse/Dog Racing', FALSE, NOW(), NOW()),
        (7829, 'Motion Pictures and Video Tape Production and Distribution', FALSE, NOW(), NOW()),
        (7832, 'Motion Picture Theaters', FALSE, NOW(), NOW()),
        (7841, 'Video Tape Rental Stores', FALSE, NOW(), NOW()),
        (7911, 'Dance Halls, Studios and Schools', FALSE, NOW(), NOW()),
        (7922, 'Theatrical Producers (Except Motion Pictures), Ticket Agencies', FALSE, NOW(), NOW()),
        (7929, 'Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)', FALSE, NOW(), NOW()),
        (7932, 'Billiard and Pool Establishments', FALSE, NOW(), NOW()),
        (7933, 'Bowling Alleys', FALSE, NOW(), NOW()),
        (7941, 'Commercial Sports, Athletic Fields, Professional Sport Clubs, and Sport Promoters', FALSE, NOW(), NOW()),
        (7991, 'Tourist Attractions and Exhibits', FALSE, NOW(), NOW()),
        (7992, 'Golf Courses – Public', FALSE, NOW(), NOW()),
        (7993, 'Video Amusement Game Supplies', FALSE, NOW(), NOW()),
        (7994, 'Video Game Arcades/Establishments', FALSE, NOW(), NOW()),
        (7995, 'Betting (including Lottery Tickets, Casino Gaming Chips, Off-track Betting and Wagers at Race Tracks)', FALSE, NOW(), NOW()),
        (7996, 'Amusement Parks, Carnivals, Circuses, Fortune Tellers', FALSE, NOW(), NOW()),
        (7997, 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses', FALSE, NOW(), NOW()),
        (7998, 'Aquariums, Sea-aquariums, Dolphinariums', FALSE, NOW(), NOW()),
        (7999, 'Recreation Services (Not Elsewhere Classified)', FALSE, NOW(), NOW()),
        (8021, 'Dentists and Orthodontists', FALSE, NOW(), NOW()),
        (8031, 'Osteopaths', FALSE, NOW(), NOW()),
        (8041, 'Chiropractors', FALSE, NOW(), NOW()),
        (8042, 'Optometrists and Ophthalmologists', FALSE, NOW(), NOW()),
        (8043, 'Opticians, Opticians Goods and Eyeglasses', FALSE, NOW(), NOW()),
        (8044, 'Opticians, Optical Goods, and Eyeglasses (no longer validfor first presentments)', FALSE, NOW(), NOW()),
        (8049, 'Podiatrists and Chiropodists', FALSE, NOW(), NOW()),
        (8050, 'Nursing and Personal Care Facilities', FALSE, NOW(), NOW()),
        (8062, 'Hospitals', FALSE, NOW(), NOW()),
        (8071, 'Medical and Dental Laboratories', FALSE, NOW(), NOW()),
        (8099, 'Medical Services and Health Practitioners (Not Elsewhere Classified)', FALSE, NOW(), NOW()),
        (8111, 'Legal Services and Attorneys', FALSE, NOW(), NOW()),
        (8211, 'Elementary and Secondary Schools', FALSE, NOW(), NOW()),
        (8220, 'Colleges, Junior Colleges, Universities, and ProfessionalSchools', FALSE, NOW(), NOW()),
        (8241, 'Correspondence Schools', FALSE, NOW(), NOW()),
        (8244, 'Business and Secretarial Schools', FALSE, NOW(), NOW()),
        (8249, 'Vocational Schools and Trade Schools', FALSE, NOW(), NOW()),
        (8299, 'Schools and Educational Services ( Not Elsewhere Classified)', FALSE, NOW(), NOW()),
        (8351, 'Child Care Services', FALSE, NOW(), NOW()),
        (8398, 'Charitable and Social Service Organizations', FALSE, NOW(), NOW()),
        (8641, 'Civic, Fraternal, and Social Associations', FALSE, NOW(), NOW()),
        (8651, 'Political Organizations', FALSE, NOW(), NOW()),
        (8661, 'Religious Organizations', FALSE, NOW(), NOW()),
        (8675, 'Automobile Associations', FALSE, NOW(), NOW()),
        (8699, 'Membership Organizations ( Not Elsewhere Classified)', FALSE, NOW(), NOW()),
        (8734, 'Testing Laboratories ( non-medical)', FALSE, NOW(), NOW()),
        (8911, 'Architectural – Engineering and Surveying Services', FALSE, NOW(), NOW()),
        (8931, 'Accounting, Auditing, and Bookkeeping Services', FALSE, NOW(), NOW()),
        (8999, 'Professional Services ( Not Elsewhere Defined)', FALSE, NOW(), NOW()),
        (9211, 'Court Costs, including Alimony and Child Support', FALSE, NOW(), NOW()),
        (9222, 'Fines', FALSE, NOW(), NOW()),
        (9223, 'Bail and Bond Payments', FALSE, NOW(), NOW()),
        (9311, 'Tax Payments', FALSE, NOW(), NOW()),
        (9399, 'Government Services ( Not Elsewhere Classified)', FALSE, NOW(), NOW()),
        (9402, 'Postal Services – Government Only', FALSE, NOW(), NOW()),
        (9405, 'Intra – Government Transactions', FALSE, NOW(), NOW()),
        (9700, 'Automated Referral Service ( For Visa Only)', FALSE, NOW(), NOW()),
        (9701, 'Visa Credential Service ( For Visa Only)', FALSE, NOW(), NOW()),
        (9702, 'GCAS Emergency Services ( For Visa Only)', FALSE, NOW(), NOW()),
        (9950, 'Intra – Company Purchases ( For Visa Only)', FALSE, NOW(), NOW()),

        ON CONFLICT (mcc_code) DO NOTHING
    """)


def downgrade() -> None:
    """Remove all seed data from mcc_codes."""
    op.execute("DELETE FROM mcc_codes")
