version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    image: ${REGISTRY}/${IMAGE_PREFIX}/frontend:latest
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  account_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/account_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD_ENCODED}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
      - USER_SERVICE_URL=http://user_service:8000
      - EXPENSE_SERVICE_URL=http://expense_service:8000
      - INCOME_SERVICE_URL=http://income_service:8000
      - CURRENCY_SERVICE_URL=http://currency_service:8000
    depends_on:
      - redis
    restart: unless-stopped

  category_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/category_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    restart: unless-stopped

  currency_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/currency_service:latest
    environment:
      - cors_origins=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    restart: unless-stopped

  debt_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/debt_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    restart: unless-stopped

  expense_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/expense_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    depends_on:
      - redis
    restart: unless-stopped

  goals_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/goals_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    restart: unless-stopped

  income_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/income_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    depends_on:
      - redis
    restart: unless-stopped

  pdf_parser_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/pdf_parser_service:latest
    restart: unless-stopped

  recurring_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/recurring_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    restart: unless-stopped

  user_service:
    image: ${REGISTRY}/${IMAGE_PREFIX}/user_service:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - INTERNAL_SECRET_TOKEN=${INTERNAL_SECRET_TOKEN}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://65.108.50.122,https://65.108.50.122
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  caddy_data:
  caddy_config: