hcloud_token   = "jqHcoCW2VH0DSy1kIhrW8XMOawE8fw3AFL84nF4BDlkBZqKNSwaIGjA5SVSbsxN3"
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPsVKD80VbeIBfzUwOmNtnHqRo3lHuvrODdDL1mUJG06 gha-deploy"
project_name   = "accounting-app"
location       = "hel1"
server_type    = "cpx21"
server_image   = "ubuntu-22.04"
db_name        = "appdb"
db_user        = "appuser"
