"""remove_subcategory_id_from_expenses

Revision ID: 9c057e799acd
Revises: c7f9d535401f
Create Date: 2025-09-23 16:04:42.858830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c057e799acd'
down_revision: Union[str, None] = 'c7f9d535401f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_subcategory_id'), table_name='expenses')
    op.drop_column('expenses', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_subcategory_id'), 'expenses', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###
