"""add_currency_to_expenses

Revision ID: c8ce19e9fd1b
Revises: e2c3e2288f33
Create Date: 2025-10-01 23:45:10.272986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ce19e9fd1b'
down_revision: Union[str, None] = 'e2c3e2288f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('expenses', sa.Column('currency', sa.String(length=3), nullable=True))
    
    # Update existing records to have default currency
    op.execute("UPDATE expenses SET currency = 'USD' WHERE currency IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('expenses', 'currency', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
