"""Add account_id to expenses

Revision ID: e2c3e2288f33
Revises: 9c057e799acd
Create Date: 2025-10-01 22:20:25.665454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c3e2288f33'
down_revision: Union[str, None] = '9c057e799acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_account_id'), 'expenses', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_account_id'), table_name='expenses')
    op.drop_column('expenses', 'account_id')
    # ### end Alembic commands ###
