name: Build, Push and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '*/app/**'
      - '**/Dockerfile'
      - '.github/workflows/build-and-push.yml'
      - '.github/actions/**'
      - 'deploy/**'
  workflow_dispatch:
    inputs:
      services:
        description: "Space-separated services to deploy (e.g., frontend account_service)"
        required: false
        default: "frontend account_service category_service expense_service income_service user_service"

concurrency:
  group: build-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ${{ secrets.REGISTRY || 'docker.io' }}
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX || secrets.DOCKER_USERNAME || github.repository_owner }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push images
        uses: ./.github/actions/build-push
        with:
          registry: ${{ env.REGISTRY }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          services: ${{ github.event.inputs.services || 'frontend account_service category_service currency_service debt_service expense_service goals_service income_service pdf_parser_service recurring_service user_service' }}

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          host: ${{ secrets.HZ_HOST }}
          user: ${{ secrets.HZ_USER || 'root' }}
          ssh-private-key: ${{ secrets.HZ_SSH_KEY }}
          registry: ${{ env.REGISTRY }}
          image-prefix: ${{ secrets.IMAGE_PREFIX || secrets.DOCKER_USERNAME || github.repository_owner }}
          db-host: ${{ secrets.DB_HOST || '65.21.159.67' }}
          db-port: ${{ secrets.DB_PORT || '5432' }}
          db-name: ${{ secrets.DB_NAME || 'appdb' }}
          db-user: ${{ secrets.DB_USER || 'appuser' }}
          db-password: ${{ secrets.DB_PASSWORD }}
          services: ${{ github.event.inputs.services || 'frontend account_service category_service currency_service debt_service expense_service goals_service income_service pdf_parser_service recurring_service user_service' }}
