name: Deploy to Hetzner

on:
  workflow_dispatch:
    inputs:
      services:
        description: "Space-separated services to deploy (e.g., frontend account_service)"
        required: false
        default: "frontend account_service category_service expense_service income_service user_service"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HZ_SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HZ_HOST }} >> ~/.ssh/known_hosts

      - name: Pull new images and restart services
        env:
          REGISTRY: ${{ secrets.REGISTRY || 'ghcr.io' }}
          IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX || github.repository }}
          SERVICES: ${{ github.event.inputs.services }}
        run: |
          set -euo pipefail
          HOST=${{ secrets.HZ_HOST }}
          USER=${{ secrets.HZ_USER || 'ubuntu' }}

          # default set of services if not provided
          if [ -z "${SERVICES:-}" ]; then
            SERVICES="frontend account_service category_service currency_service debt_service expense_service goals_service income_service pdf_parser_service recurring_service user_service"
          fi

          # Remote script: pull latest images and recreate containers via compose
          ssh -o StrictHostKeyChecking=no "$USER@$HOST" bash -s <<'EOS'
          set -euo pipefail
          cd ~/app || mkdir -p ~/app && cd ~/app

          # Expect a docker-compose.yml in this directory configured to use images like REGISTRY/IMAGE_PREFIX/<svc>:latest
          echo "Pulling latest images..."
          docker compose pull
          echo "Recreating services: $SERVICES"
          docker compose up -d $SERVICES

          echo "Pruning old images..."
          docker image prune -f || true
EOS

